"""Email delivery service using Resend."""

import resend
from app.config import get_settings


async def send_summary_email(to_email: str, summary_html: str, filename: str) -> dict:
    """
    Send the AI-generated sales summary via email.
    
    Args:
        to_email: Recipient email address.
        summary_html: HTML-formatted sales brief.
        filename: Original uploaded filename for the subject line.
    
    Returns:
        Resend API response dict.
    """
    settings = get_settings()

    if not settings.RESEND_API_KEY:
        raise ValueError("RESEND_API_KEY is not configured. Set it in your .env file.")

    resend.api_key = settings.RESEND_API_KEY

    email_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
                   color: #333; line-height: 1.6; max-width: 700px; margin: 0 auto; padding: 20px; }}
            h1 {{ color: #1a1a2e; border-bottom: 3px solid #6c63ff; padding-bottom: 10px; }}
            h2 {{ color: #6c63ff; }}
            h3 {{ color: #16213e; }}
            ul {{ padding-left: 20px; }}
            li {{ margin-bottom: 6px; }}
            .footer {{ margin-top: 30px; padding-top: 15px; border-top: 1px solid #eee; 
                       font-size: 12px; color: #999; }}
        </style>
    </head>
    <body>
        <h1>📊 Sales Insight Report</h1>
        <p><strong>Source file:</strong> {filename}</p>
        <hr>
        {summary_html}
        <div class="footer">
            <p>Generated by <strong>Sales Insight Automator</strong> — Powered by Rabbitt AI</p>
        </div>
    </body>
    </html>
    """

    params: resend.Emails.SendParams = {
        "from": settings.EMAIL_FROM,
        "to": [to_email],
        "subject": f"📊 Sales Insight Report — {filename}",
        "html": email_html,
    }

    response = resend.Emails.send(params)
    return response
